name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the form below to help us understand and reproduce the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting a bug report.
      options:
        - label: I have searched existing issues to ensure this hasn't been reported before
          required: true
        - label: I am using the latest version of the TYPO3 Upgrade Analyzer
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Analyze TYPO3 installation at '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: TYPO3 Upgrade Analyzer Version
      description: Run `./bin/typo3-analyzer --version` to get the version
      placeholder: v1.0.0
    validations:
      required: true

  - type: input
    id: typo3-version
    attributes:
      label: TYPO3 Version Being Analyzed
      description: What version of TYPO3 are you trying to analyze?
      placeholder: 11.5.46
    validations:
      required: true

  - type: input
    id: target-version
    attributes:
      label: Target TYPO3 Version
      description: What TYPO3 version are you upgrading to?
      placeholder: 12.4.0
    validations:
      required: true

  - type: dropdown
    id: php-version
    attributes:
      label: PHP Version
      description: What version of PHP are you using?
      options:
        - 8.1
        - 8.2
        - 8.3
        - 8.4
        - Other (specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Docker
        - Other (specify in additional context)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please provide relevant error logs or output
      placeholder: Paste error logs here...
      render: text

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, configuration files, etc.)
      placeholder: Any additional information...