services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Commands
  CPSIT\UpgradeAnalyzer\Application\Command\:
    resource: '../src/Application/Command/*'
    public: true

  # Infrastructure services

  CPSIT\UpgradeAnalyzer\Infrastructure\Analyzer\:
    resource: '../src/Infrastructure/Analyzer/*'
    tags: ['analyzer']

  # Override VersionAvailabilityAnalyzer to include GitRepositoryAnalyzer
  CPSIT\UpgradeAnalyzer\Infrastructure\Analyzer\VersionAvailabilityAnalyzer:
    public: true
    arguments:
      - '@CPSIT\UpgradeAnalyzer\Infrastructure\ExternalTool\TerApiClient'
      - '@CPSIT\UpgradeAnalyzer\Infrastructure\ExternalTool\PackagistClient'
      - '@CPSIT\UpgradeAnalyzer\Infrastructure\ExternalTool\GitRepositoryAnalyzer'
      - '@logger'
    tags: ['analyzer']

  CPSIT\UpgradeAnalyzer\Infrastructure\ExternalTool\:
    resource: '../src/Infrastructure/ExternalTool/*'

  # Shared services
  CPSIT\UpgradeAnalyzer\Shared\Configuration\:
    resource: '../src/Shared/Configuration/*'

  # Twig
  Twig\Environment:
    arguments:
      $loader: '@twig.loader'
      $options:
        cache: '%app.root_dir%/var/cache/twig'
        debug: false

  twig.loader:
    class: Twig\Loader\FilesystemLoader
    arguments:
      - '%app.resources_dir%/templates'

  # PHP Parser
  PhpParser\Parser:
    factory: ['PhpParser\ParserFactory', 'createForHostVersion']

  # Git Provider Factory and implementations
  CPSIT\UpgradeAnalyzer\Infrastructure\ExternalTool\GitProvider\GitProviderFactory:
    arguments:
      - [
          '@CPSIT\UpgradeAnalyzer\Infrastructure\ExternalTool\GitProvider\GitHubClient'
        ]
      - '@logger'

  # Git Provider Implementations
  CPSIT\UpgradeAnalyzer\Infrastructure\ExternalTool\GitProvider\GitHubClient:
    arguments:
      - '@http_client'
      - '@logger'
      - '%env(GITHUB_ACCESS_TOKEN)%'

  # Git Repository Analyzer
  CPSIT\UpgradeAnalyzer\Infrastructure\ExternalTool\GitRepositoryAnalyzer:
    arguments:
      - '@CPSIT\UpgradeAnalyzer\Infrastructure\ExternalTool\GitProvider\GitProviderFactory'
      - '@CPSIT\UpgradeAnalyzer\Infrastructure\ExternalTool\GitVersionParser'
      - '@logger'

  # Git Version Parser
  CPSIT\UpgradeAnalyzer\Infrastructure\ExternalTool\GitVersionParser: ~

  # Configuration Parsers
  CPSIT\UpgradeAnalyzer\Infrastructure\Parser\:
    resource: '../src/Infrastructure/Parser/*'
    exclude: '../src/Infrastructure/Parser/Exception/*'
    tags: ['configuration_parser']

  # PHP Configuration Parser
  CPSIT\UpgradeAnalyzer\Infrastructure\Parser\PhpConfigurationParser:
    arguments:
      - '@PhpParser\Parser'
      - '@logger'
    tags: ['configuration_parser']

  # YAML Configuration Parser
  CPSIT\UpgradeAnalyzer\Infrastructure\Parser\YamlConfigurationParser:
    arguments:
      - '@logger'
    tags: ['configuration_parser']

  # Configuration Discovery Service
  CPSIT\UpgradeAnalyzer\Infrastructure\Discovery\ConfigurationDiscoveryService:
    arguments:
      - !tagged_iterator 'configuration_parser'
      - '@logger'

  # Discovery Services
  CPSIT\UpgradeAnalyzer\Infrastructure\Discovery\:
    resource: '../src/Infrastructure/Discovery/*'
    exclude: '../src/Infrastructure/Discovery/ConfigurationDiscoveryService.php'
    tags: ['discovery_service']

  # Extension Discovery Service
  CPSIT\UpgradeAnalyzer\Infrastructure\Discovery\ExtensionDiscoveryService:
    public: true
    arguments:
      - '@logger'
      - '@CPSIT\UpgradeAnalyzer\Infrastructure\Configuration\ConfigurationService'
      - '@CPSIT\UpgradeAnalyzer\Infrastructure\Cache\CacheService'
    tags: ['discovery_service']

  # Installation Discovery Service with Configuration Discovery
  CPSIT\UpgradeAnalyzer\Infrastructure\Discovery\InstallationDiscoveryService:
    public: true
    arguments:
      - !tagged_iterator 'detection_strategy'
      - !tagged_iterator 'validation_rule'
      - '@CPSIT\UpgradeAnalyzer\Infrastructure\Discovery\ConfigurationDiscoveryService'
      - '@logger'
      - '@CPSIT\UpgradeAnalyzer\Infrastructure\Configuration\ConfigurationService'
      - '@CPSIT\UpgradeAnalyzer\Infrastructure\Cache\CacheService'

  # Version Strategies
  CPSIT\UpgradeAnalyzer\Infrastructure\Discovery\ComposerVersionStrategy:
    tags: ['version_strategy']

  # Version Extractor
  CPSIT\UpgradeAnalyzer\Infrastructure\Discovery\VersionExtractor:
    arguments:
      - !tagged_iterator 'version_strategy'
      - '@logger'

  # Detection Strategies
  CPSIT\UpgradeAnalyzer\Infrastructure\Discovery\ComposerInstallationDetector:
    tags: ['detection_strategy']

  # Configuration Service
  CPSIT\UpgradeAnalyzer\Infrastructure\Configuration\ConfigurationService:
    public: true
    arguments:
      - '@logger'

  # Configuration Service Interface Alias
  CPSIT\UpgradeAnalyzer\Infrastructure\Configuration\ConfigurationServiceInterface:
    alias: CPSIT\UpgradeAnalyzer\Infrastructure\Configuration\ConfigurationService

  # Cache Service
  CPSIT\UpgradeAnalyzer\Infrastructure\Cache\CacheService:
    public: true
    arguments:
      - '@logger'
      - '%app.root_dir%'