services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Commands
  CPSIT\UpgradeAnalyzer\Application\Command\:
    resource: '../src/Application/Command/*'
    public: true

  # Infrastructure services

  CPSIT\UpgradeAnalyzer\Infrastructure\Analyzer\:
    resource: '../src/Infrastructure/Analyzer/*'
    tags: ['analyzer']

  CPSIT\UpgradeAnalyzer\Infrastructure\ExternalTool\:
    resource: '../src/Infrastructure/ExternalTool/*'

  # Shared services
  CPSIT\UpgradeAnalyzer\Shared\Configuration\:
    resource: '../src/Shared/Configuration/*'

  # Twig
  Twig\Environment:
    arguments:
      $loader: '@twig.loader'
      $options:
        cache: '%app.root_dir%/var/cache/twig'
        debug: false

  twig.loader:
    class: Twig\Loader\FilesystemLoader
    arguments:
      - '%app.resources_dir%/templates'

  # PHP Parser
  PhpParser\Parser:
    class: PhpParser\Parser\Php7
    factory: ['PhpParser\ParserFactory', 'create']
    arguments:
      - 4  # PhpParser\ParserFactory::PREFER_PHP7