<?php

declare(strict_types=1);

// PackageStates.php v5 format as generated by TYPO3 in Composer mode.
// In Composer mode, entries contain only 'packagePath' — no 'state' key.
// The ExtensionDiscoveryService must NOT use this file for activation state in
// Composer installations (regression fixture for issue #163).
return [
    'packages' => [
        'typo3/cms-core' => [
            'packagePath' => 'vendor/typo3/cms-core/',
        ],
        'typo3/cms-frontend' => [
            'packagePath' => 'vendor/typo3/cms-frontend/',
        ],
        'georgringer/news' => [
            'packagePath' => 'vendor/georgringer/news/',
        ],
        'example/powermail' => [
            'packagePath' => 'vendor/example/powermail/',
        ],
    ],
    'version' => 5,
];
